package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"gitlab.com/pragmticreviews/graphql-server/graph/model"
)

// AddPerson is the resolver for the AddPerson field.
// func (r *mutationResolver) AddPerson(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
// 	panic(fmt.Errorf("not implemented: AddPerson - AddPerson"))
// }

// People is the resolver for the people field.
func (r *queryResolver) People(ctx context.Context) ([], error) {
	panic(fmt.Errorf("not implemented: People - People"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
